// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDrives() {
  return window['go']['main']['App']['GetDrives']();
}

export function GetFolders(arg1) {
  return window['go']['main']['App']['GetFolders'](arg1);
}

export function GetHome() {
  return window['go']['main']['App']['GetHome']();
}

export function GetOS() {
  return window['go']['main']['App']['GetOS']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Test() {
  return window['go']['main']['App']['Test']();
}
