// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {disk} from '../models';
import {main} from '../models';

export function GetDrives():Promise<Array<disk.PartitionStat>>;

export function GetFolders(arg1:string):Promise<Array<string>>;

export function GetHome():Promise<Array<main.Directory>>;

export function GetOS():Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function Test():Promise<number>;
